In [3]:
%matplotlib inline
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


Data Generation
===

Solution
===

In [5]:
df = pd.read_csv('./lpmc10.dat')
df

trip_id\thousehold_id\tperson_n\ttrip_n\ttravel_mode\tpurpose\tfueltype\tfaretype\tbus_scale\tsurvey_year\ttravel_year\ttravel_month\ttravel_date\tday_of_week\tstart_time\tage\tfemale\tdriving_license\tcar_ownership\tdistance\tdur_walking\tdur_cycling\tdur_pt_access\tdur_pt_rail\tdur_pt_bus\tdur_pt_int\tpt_interchanges\tdur_driving\tcost_transit\tcost_driving_fuel\tcost_driving_ccharge\tdriving_traffic_percent
0     20\t5\t1\t0\t4\t3\t1\t5\t0.0\t1\t2012\t4\t1\t7...                                                                                                                                                                                                                                                                                                                                                                           
1     41\t9\t3\t0\t4\t3\t1\t5\t0.0\t1\t2012\t4\t1\t7...                                                                                                                                                                                                                                                                                                                                                                           
2     69\t13\t2\t1\t4\t3\t1\t1\t1.0\t1\t2012\t4\t1\t...                                                                                                                                                                                                                                                                                                                                                                           
3     102\t20\t2\t0\t2\t3\t1\t1\t1.0\t1\t2012\t4\t1\...                                                                                                                                                                                                                                                                                                                                                                           
4     105\t21\t0\t1\t4\t3\t1\t1\t1.0\t1\t2012\t4\t1\...                                                                                                                                                                                                                                                                                                                                                                           
...                                                 ...                                                                                                                                                                                                                                                                                                                                                                           
4995  80998\t17591\t0\t5\t4\t3\t1\t5\t0.0\t3\t2015\t...                                                                                                                                                                                                                                                                                                                                                                           
4996  81000\t17592\t0\t0\t3\t3\t6\t5\t0.0\t3\t2015\t...                                                                                                                                                                                                                                                                                                                                                                           
4997  81015\t17597\t0\t3\t4\t3\t1\t5\t0.0\t3\t2015\t...                                                                                                                                                                                   

In [29]:
def standardize(x):
    
    centered_data = x-np.mean(x,axis=0)
    std_data = centered_data / np.std(centered_data)

    return centered_data

std_data = standardize(data)

In [30]:
print(std_data, "\n\n", np.mean(std_data, axis=0), "\n\n", np.std(std_data, axis=0))

[[ 0.20344878 -0.41972612  0.09397858  0.22671326  0.05947394]
 [-0.34307522 -0.24241521  0.22086106 -0.35297979 -0.35069326]
 [ 0.11748795  0.51291527 -0.53572138 -0.00989836  0.37358789]
 [ 0.0446542   0.28127725 -0.24779358  0.3956835   0.27554271]
 [-0.0253275  -0.29830802 -0.16632889  0.15204299  0.0028001 ]
 [-0.13385787  0.17728891 -0.02653141  0.12830656  0.16200588]
 [ 0.23735133  0.08116908  0.36897923 -0.20285454 -0.34857372]
 [-0.26717181 -0.32649371  0.28901168 -0.47519431  0.18725407]
 [-0.02028571  0.37880892 -0.34072211  0.33475968 -0.08738043]
 [ 0.18677583 -0.14451637  0.34426683 -0.19657899 -0.27401718]] 

 [-3.33066907e-17  2.22044605e-17 -1.11022302e-17  0.00000000e+00
  6.66133815e-17] 

 [0.18880201 0.31226926 0.29810476 0.28105224 0.24648668]
